export const homeCategories = [
  { id: 'hero-banner', label: 'Hero Banner', mappedId: 'hero' },
  { id: 'hero-carousel', label: 'Hero Carousel', mappedId: 'hero-carousel' },
  { id: 'promotional-banner', label: 'Promotional Banner', mappedId: 'promotional' },
  { id: 'featured-categories', label: 'Featured Categories', mappedId: 'featured-categories' },
  { id: 'category-grid', label: 'Category Grid', mappedId: 'category-grid' },
  { id: 'featured-collections', label: 'Featured Collections', mappedId: 'featured-collections' },
  { id: 'product-grid', label: 'Product Grid', mappedId: 'product-grids' },
  { id: 'product-carousel', label: 'Product Carousel', mappedId: 'product-carousels' },
  { id: 'best-sellers', label: 'Best Sellers', mappedId: 'best-sellers' },
  { id: 'new-arrivals', label: 'New Arrivals', mappedId: 'new-arrivals' },
  { id: 'trending-products', label: 'Trending Products', mappedId: 'trending-products' },
  { id: 'sale-products', label: 'Sale Products', mappedId: 'sale-products' },
  { id: 'flash-sale', label: 'Flash Sale', mappedId: 'flash-sale' },
  { id: 'featured-product', label: 'Featured Product', mappedId: 'featured-product' },
  { id: 'image-text', label: 'Image + Text', mappedId: 'image-text' },
  { id: 'split-image-content', label: 'Split Image Content', mappedId: 'split-image' },
  { id: 'promotional-cards', label: 'Promotional Cards', mappedId: 'promotional-cards' },
  { id: 'why-choose-us', label: 'Why Choose Us', mappedId: 'why-choose-us' },
  { id: 'brand-showcase', label: 'Brand Showcase', mappedId: 'brand-showcase' },
  { id: 'testimonials', label: 'Testimonials', mappedId: 'testimonials' },
  { id: 'customer-reviews', label: 'Customer Reviews', mappedId: 'customer-reviews' },
  { id: 'video-showcase', label: 'Video Showcase', mappedId: 'video-showcase' },
  { id: 'blog-highlights', label: 'Blog Highlights', mappedId: 'blog-highlights' },
  { id: 'buying-guide', label: 'Buying Guide', mappedId: 'buying-guide' },
  { id: 'faq', label: 'FAQ', mappedId: 'faq' },
  { id: 'newsletter', label: 'Newsletter', mappedId: 'newsletter' },
];

export const productCategories = [
  { id: 'product-gallery', label: 'Product Gallery', mappedId: 'product-gallery' },
  { id: 'product-information', label: 'Product Information', mappedId: 'product-information' },
  { id: 'product-purchase-section', label: 'Product Purchase Section', mappedId: 'product-purchase-section' },
  { id: 'product-description', label: 'Product Description', mappedId: 'product-description' },
  { id: 'product-highlights', label: 'Product Highlights', mappedId: 'product-highlights' },
  { id: 'product-specifications', label: 'Product Specifications', mappedId: 'product-specifications' },
  { id: 'product-features', label: 'Product Features', mappedId: 'product-features' },
  { id: 'what-s-included', label: "What's Included", mappedId: 'what-s-included' },
  { id: 'size-guide', label: 'Size Guide', mappedId: 'size-guide' },
  { id: 'product-card', label: 'Product Card', mappedId: 'product-card' },
  { id: 'warranty-information', label: 'Warranty Information', mappedId: 'warranty-information' },
  { id: 'shipping-delivery-information', label: 'Shipping & Delivery Information', mappedId: 'shipping-delivery-information' },
  { id: 'return-refund-information', label: 'Return & Refund Information', mappedId: 'return-refund-information' },
  { id: 'payment-information', label: 'Payment Information', mappedId: 'payment-information' },
  { id: 'product-frequently-bought-together', label: 'Frequently Bought Together', mappedId: 'product-frequently-bought-together' },
  { id: 'product-bundles', label: 'Product Bundles', mappedId: 'product-bundles' },
  { id: 'related-products', label: 'Related Products', mappedId: 'related-products' },
  { id: 'similar-products', label: 'Similar Products', mappedId: 'similar-products' },
  { id: 'product-recommended-products', label: 'Recommended Products', mappedId: 'product-recommended-products' },
  { id: 'customer-reviews-product', label: 'Customer Reviews', mappedId: 'customer-reviews' },
  { id: 'review-summary', label: 'Review Summary', mappedId: 'review-summary' },
  { id: 'customer-review-gallery', label: 'Customer Review Gallery', mappedId: 'customer-review-gallery' },
  { id: 'questions-answers', label: 'Questions & Answers', mappedId: 'questions-answers' },
  { id: 'product-faq', label: 'Product FAQ', mappedId: 'product-faq' },
  { id: 'brand-information', label: 'Brand Information', mappedId: 'brand-information' },
];

export const cartCategories = [
  { id: 'cart-items-section', label: 'Cart Items Section', mappedId: 'cart-items-section' },
  { id: 'cart-summary', label: 'Cart Summary', mappedId: 'cart-summary' },
  { id: 'cart-offers', label: 'Cart Offers', mappedId: 'cart-offers' },
  { id: 'coupon-discount-section', label: 'Coupon / Discount Section', mappedId: 'coupon-discount-section' },
  { id: 'shipping-information', label: 'Shipping Information', mappedId: 'shipping-information' },
  { id: 'free-shipping-progress', label: 'Free Shipping Progress', mappedId: 'free-shipping-progress' },
  { id: 'cart-recommended-products', label: 'Recommended Products', mappedId: 'cart-recommended-products' },
  { id: 'cart-frequently-bought-together', label: 'Frequently Bought Together', mappedId: 'cart-frequently-bought-together' },
  { id: 'recently-viewed-products', label: 'Recently Viewed Products', mappedId: 'recently-viewed-products' },
  { id: 'empty-cart-section', label: 'Empty Cart Section', mappedId: 'empty-cart-section' },
];

export const checkoutCategories = [
  { id: 'customer-information', label: 'Customer Information', mappedId: 'customer-information' },
  { id: 'shipping-address', label: 'Shipping Address', mappedId: 'shipping-address' },
  { id: 'billing-address', label: 'Billing Address', mappedId: 'billing-address' },
  { id: 'delivery-options', label: 'Delivery Options', mappedId: 'delivery-options' },
  { id: 'payment-options', label: 'Payment Options', mappedId: 'payment-options' },
  { id: 'checkout-order-summary', label: 'Order Summary', mappedId: 'checkout-order-summary' },
  { id: 'checkout-discount-coupon', label: 'Discount / Coupon Section', mappedId: 'checkout-discount-coupon' },
  { id: 'checkout-gift-card', label: 'Gift Card Section', mappedId: 'checkout-gift-card' },
  { id: 'checkout-security-trust', label: 'Security / Trust Section', mappedId: 'checkout-security-trust' },
];

export const orderCategories = [
  { id: 'order-success', label: 'Order Success Section', mappedId: 'order-success' },
  { id: 'order-summary', label: 'Order Summary', mappedId: 'order-summary' },
  { id: 'order-delivery-information', label: 'Delivery Information', mappedId: 'order-delivery-information' },
  { id: 'order-recommended-products', label: 'Recommended Products', mappedId: 'order-recommended-products' },
  { id: 'order-customer-support', label: 'Customer Support', mappedId: 'order-customer-support' },
  { id: 'order-continue-shopping', label: 'Continue Shopping', mappedId: 'order-continue-shopping' },
];

export const accountCategories = [
  { id: 'account-overview', label: 'Account Overview', mappedId: 'account-overview' },
  { id: 'account-profile-information', label: 'Profile Information', mappedId: 'account-profile-information' },
  { id: 'account-address-book', label: 'Address Book', mappedId: 'account-address-book' },
  { id: 'account-wishlist', label: 'Wishlist', mappedId: 'account-wishlist' },
  { id: 'account-saved-products', label: 'Saved Products', mappedId: 'account-saved-products' },
  { id: 'account-recently-viewed-products', label: 'Recently Viewed Products', mappedId: 'account-recently-viewed-products' },
  { id: 'account-reviews-ratings', label: 'Reviews & Ratings', mappedId: 'account-reviews-ratings' },
  { id: 'account-loyalty-rewards', label: 'Loyalty / Rewards', mappedId: 'account-loyalty-rewards' },
  { id: 'account-coupons-offers', label: 'Coupons & Offers', mappedId: 'account-coupons-offers' },
  { id: 'account-notification-preferences', label: 'Notification Preferences', mappedId: 'account-notification-preferences' },
];

export const offersCategories = [
  { id: 'offers-hero', label: 'Offers Hero', mappedId: 'offers-hero' },
  { id: 'offers-flash-sale', label: 'Flash Sale', mappedId: 'offers-flash-sale' },
  { id: 'offers-deals-grid', label: 'Deals Grid', mappedId: 'offers-deals-grid' },
  { id: 'offers-featured', label: 'Featured Offers', mappedId: 'offers-featured' },
  { id: 'offers-coupon', label: 'Coupon Offers', mappedId: 'offers-coupon' },
  { id: 'offers-limited-time', label: 'Limited Time Offers', mappedId: 'offers-limited-time' },
  { id: 'offers-clearance', label: 'Clearance Sale', mappedId: 'offers-clearance' },
  { id: 'offers-bundle', label: 'Bundle Offers', mappedId: 'offers-bundle' },
  { id: 'offers-free-shipping', label: 'Free Shipping Offers', mappedId: 'offers-free-shipping' },
  { id: 'offers-categories', label: 'Offer Categories', mappedId: 'offers-categories' },
  { id: 'offers-faq', label: 'Offers FAQ', mappedId: 'offers-faq' },
];

export const blogCategories = [
  { id: 'blog-hero', label: 'Blog Hero', mappedId: 'blog-hero' },
  { id: 'blog-featured-article', label: 'Featured Article', mappedId: 'blog-featured-article' },
  { id: 'blog-latest-articles', label: 'Latest Articles', mappedId: 'blog-latest-articles' },
  { id: 'blog-categories', label: 'Blog Categories', mappedId: 'blog-categories' },
  { id: 'blog-grid', label: 'Blog Grid', mappedId: 'blog-grid' },
  { id: 'blog-popular-articles', label: 'Popular Articles', mappedId: 'blog-popular-articles' },
  { id: 'blog-recent-articles', label: 'Recent Articles', mappedId: 'blog-recent-articles' },
  { id: 'blog-newsletter', label: 'Newsletter', mappedId: 'blog-newsletter' },
];

export const aboutCategories = [
  { id: 'about-hero', label: 'About Hero', mappedId: 'about-hero' },
  { id: 'about-brand-story', label: 'Brand Story', mappedId: 'about-brand-story' },
  { id: 'about-mission-vision', label: 'Mission & Vision', mappedId: 'about-mission-vision' },
  { id: 'about-company-statistics', label: 'Company Statistics', mappedId: 'about-company-statistics' },
  { id: 'about-image-content', label: 'Image + Content', mappedId: 'about-image-content' },
  { id: 'about-company-timeline', label: 'Company Timeline', mappedId: 'about-company-timeline' },
  { id: 'about-brand-values', label: 'Brand Values', mappedId: 'about-brand-values' },
  { id: 'about-team-showcase', label: 'Team Showcase', mappedId: 'about-team-showcase' },
  { id: 'about-certifications', label: 'Certifications', mappedId: 'about-certifications' },
  { id: 'about-partners-brands', label: 'Partners / Brands', mappedId: 'about-partners-brands' },
  { id: 'about-cta-banner', label: 'CTA Banner', mappedId: 'about-cta-banner' },
];


export const contactCategories = [
  { id: 'contact-hero', label: 'Contact Hero', mappedId: 'contact-hero' },
  { id: 'contact-information', label: 'Contact Information', mappedId: 'contact-information' },
  { id: 'business-information', label: 'Business Information', mappedId: 'business-information' },
  { id: 'store-locations', label: 'Store Locations', mappedId: 'store-locations' },
  { id: 'location-map', label: 'Location Map', mappedId: 'location-map' },
  { id: 'support-information', label: 'Support Information', mappedId: 'support-information' },
  { id: 'contact-faq', label: 'Contact FAQ', mappedId: 'contact-faq' },
];

export const errorCategories = [
  { id: '404-page-content', label: '404 Page Content', mappedId: '404-page-content' },
  { id: 'no-search-results', label: 'No Search Results', mappedId: 'no-search-results' },
  { id: 'empty-cart', label: 'Empty Cart', mappedId: 'empty-cart' },
  { id: 'empty-wishlist', label: 'Empty Wishlist', mappedId: 'empty-wishlist' },
  { id: 'empty-order-history', label: 'Empty Order History', mappedId: 'empty-order-history' },
];

export const globalCategories = [
  { id: 'global-header', label: 'Header', mappedId: 'global-header' },
  { id: 'global-mega-navigation', label: 'Mega Navigation', mappedId: 'global-mega-navigation' },
  { id: 'global-announcement-bar', label: 'Announcement Bar', mappedId: 'global-announcement-bar' },
  { id: 'global-hero-banner', label: 'Hero Banner', mappedId: 'global-hero-banner' },
  { id: 'global-promotional-banner', label: 'Promotional Banner', mappedId: 'global-promotional-banner' },
  { id: 'global-product-grid', label: 'Product Grid', mappedId: 'global-product-grid' },
  { id: 'global-product-carousel', label: 'Product Carousel', mappedId: 'global-product-carousel' },
  { id: 'global-category-grid', label: 'Category Grid', mappedId: 'global-category-grid' },
  { id: 'global-collection-grid', label: 'Collection Grid', mappedId: 'featured-collections' },
  { id: 'global-brand-showcase', label: 'Brand Showcase', mappedId: 'brand-showcase' },
  { id: 'global-image-text', label: 'Image + Text', mappedId: 'global-image-text' },
  { id: 'global-promotional-cards', label: 'Promotional Cards', mappedId: 'global-promotional-cards' },
  { id: 'global-testimonials', label: 'Testimonials', mappedId: 'global-testimonials' },
  { id: 'global-customer-reviews', label: 'Customer Reviews', mappedId: 'global-customer-reviews' },
  { id: 'global-video-section', label: 'Video Section', mappedId: 'global-video-section' },
  { id: 'global-blog-grid', label: 'Blog Grid', mappedId: 'global-blog-grid' },
  { id: 'global-faq', label: 'FAQ', mappedId: 'global-faq' },
  { id: 'global-newsletter', label: 'Newsletter', mappedId: 'global-newsletter' },
  { id: 'global-trust-certification', label: 'Trust / Certification Section', mappedId: 'global-trust-certification' },
  { id: 'global-cta-banner', label: 'CTA Banner', mappedId: 'global-cta-banner' },
  { id: 'global-footer', label: 'Footer', mappedId: 'global-footer' },
];
