const fs = require('fs');
const path = require('path');

const gridFilePath = path.join(process.cwd(), 'src', 'components', 'section-library', 'SectionLibraryGrid.tsx');
let gridCode = fs.readFileSync(gridFilePath, 'utf8');

const uniqueTitles = [
  'AURORA GLASS BENTO PRODUCT CAROUSEL (ANIMATION: FLOAT & GLOW INTERACTIVE HORIZONTAL SNAP)',
  'CYBERPUNK MATRIX HUD CAROUSEL SLIDER (ANIMATION: GLITCH SHIMMER & SCANLINE PULSE TRACK)',
  'NEUMORPHIC SOFT EMBOSSED DUAL-SHADOW CAROUSEL (ANIMATION: TACTILE DEEP PRESS & DUAL SHADOW EMBOSS)',
  'CLAYMORPHIC 3D POP ELASTIC CAROUSEL (ANIMATION: 3D CLAY ELEVATION & ELASTIC BOUNCE SCROLL)',
  'SUB-ZERO CRYO FROST SLIDER CAROUSEL (ANIMATION: ICE CRYSTAL SHADOW & FROST PULSE TRACK)',
  'RETRO 8-BIT ARCADE QUEST SLIDER (ANIMATION: PIXEL FLASH & 8-BIT BUTTON BOUNCE TRACK)',
  'SWISS ARCHITECTURAL MONOCHROME SLIDER (ANIMATION: GRID LINE DRAW & FINE LINE CROSSHAIR)',
  'GLASSMORPHIC PRISM DISPERSION SLIDER (ANIMATION: CHROMATIC REFRACTION & PRISM LIGHT TILT)',
  'GOLDEN LUXURY VINTAGE CATALOGUE CAROUSEL (ANIMATION: GOLDEN GLIMMER & SILK CROSSFADE SLIDE)',
  'BIOPHILIC ECO SPHERE DISPLAY CAROUSEL (ANIMATION: LEAF ORBIT & NATURE BREATHING PULSE TRACK)',
  'STICKER COLLAGE STREETWEAR SLIDER (ANIMATION: STICKER ROTATE ON HOVER & SLIDE-IN TRACK)',
  'VAPORWAVE 80S SYNTH RETRO CAROUSEL (ANIMATION: NEON GRID PASS & SYNTHWAVE PULSE TRACK)',
  'MINIMAL JAPANESE ZEN SPACES CAROUSEL (ANIMATION: SOFT FADE & BOTANICAL SLOW PARALLAX)',
  'SPACE EXPLORER ORBITAL CAROUSEL (ANIMATION: STAR DUST PARALLAX & GRAVITY PULL SCROLL)',
  'HOLOGRAPHIC 3D SPATIAL CAROUSEL (ANIMATION: HOLOGRAM SCAN & SPECTRUM SHINE TRACK)',
  'EDITORIAL LUXURY FASHION LOOKBOOK SLIDER (ANIMATION: SMOOTH MODEL ZOOM & METRIC SLIDE UP)',
  'KINETIC DYNAMIC TYPOGRAPHIC CAROUSEL (ANIMATION: RUNNING TEXT TICKER & ELEVATING CARDS)',
  'TACTILE PAPER CUT ART CATALOGUE SLIDER (ANIMATION: PAPER LAYER DROP SHADOW & UNFOLD SLIDE)',
  'BAUHAUS GEOMETRIC COLOR BLOCK CAROUSEL (ANIMATION: PRIMARY BLOCK SHIFT & ROTATE ICON SLIDE)',
  'CYBER ORGANIC BIOPUNK MARKETPLACE SLIDER (ANIMATION: BIO-CELL PULSE & TOXIC NEON HOVER TRACK)'
];

let newCaseBlock = `] : category === 'global-product-carousel' ? [\n`;
for (let i = 1; i <= 20; i++) {
  newCaseBlock += `      { id: 'global-product-carousel-${i}', title: 'Design ${i}: ${uniqueTitles[i-1]}', description: 'Design: ${uniqueTitles[i-1]}', previewComponent: <GlobalProductCarousel${i} /> },\n`;
}

// Replace existing global-product-carousel block in getSectionsForCategory
const regex = /\] : category === 'global-product-carousel' \? \[\s*([\s\S]*?)\s*\] : category === 'global-product-grid'/;
gridCode = gridCode.replace(regex, newCaseBlock + `] : category === 'global-product-grid'`);

fs.writeFileSync(gridFilePath, gridCode, 'utf8');
console.log('Successfully updated all 20 unique Global Product Carousel titles in SectionLibraryGrid.tsx!');
