const fs = require('fs');
const path = require('path');

const gridFilePath = path.join(process.cwd(), 'src', 'components', 'section-library', 'SectionLibraryGrid.tsx');
let gridCode = fs.readFileSync(gridFilePath, 'utf8');

const titles = [
  'AURORA GLASS BENTO PRODUCT CAROUSEL (ANIMATION: SMOOTH SNAP HORIZONTAL SCROLL & FROST GLOW)',
  'CYBERPUNK MATRIX HUD CAROUSEL SLIDER (ANIMATION: GLITCH SHIMMER & HORIZONTAL SCAN TRACK)',
  'NEUMORPHIC SOFT EMBOSSED CAROUSEL (ANIMATION: TACTILE DEEP PRESS & DUAL SHADOW EMBOSS)',
  'CLAYMORPHIC 3D POP PRODUCT CAROUSEL (ANIMATION: 3D CLAY ELEVATION & ELASTIC SCROLL BOUNCE)',
  'SUB-ZERO CRYO FROST SLIDER CAROUSEL (ANIMATION: ICE CRYSTAL SHADOW & FROST PULSE TRACK)',
  'RETRO 8-BIT ARCADE COMMERCE SLIDER (ANIMATION: PIXEL FLASH & 8-BIT BUTTON BOUNCE TRACK)',
  'SWISS ARCHITECTURAL MONOCHROME SLIDER (ANIMATION: GRID LINE DRAW & FINE LINE CROSSHAIR)',
  'GLASSMORPHIC PRISM DISPERSION SLIDER (ANIMATION: CHROMATIC REFRACTION & PRISM LIGHT TILT)',
  'GOLDEN LUXURY VINTAGE CATALOGUE CAROUSEL (ANIMATION: GOLDEN GLIMMER & SILK CROSSFADE SLIDE)',
  'BIOPHILIC ECO SPHERE DISPLAY CAROUSEL (ANIMATION: LEAF ORBIT & NATURE BREATHING PULSE TRACK)',
  'NEUMORPHIC DUAL-INSET SOFT CAROUSEL (ANIMATION: TACTILE DUAL SHADOW EMBOSS & SOFT PRESS)',
  'CLAYMORPHIC PASTEL BUBBLE CAROUSEL (ANIMATION: SOFT 3D VOLUME & ELASTIC BOUNCE SCROLL)',
  'VAPORWAVE 80S SYNTH RETRO CAROUSEL (ANIMATION: NEON GRID PASS & SYNTHWAVE PULSE TRACK)',
  'MINIMAL JAPANESE ZEN SPACES CAROUSEL (ANIMATION: SOFT FADE & BOTANICAL SLOW PARALLAX)',
  'SPACE EXPLORER ORBITAL CAROUSEL (ANIMATION: STAR DUST PARALLAX & GRAVITY PULL SCROLL)',
  'HOLOGRAPHIC 3D SPATIAL CAROUSEL (ANIMATION: HOLOGRAM SCAN & SPECTRUM SHINE TRACK)',
  'EDITORIAL LUXURY FASHION LOOKBOOK SLIDER (ANIMATION: SMOOTH MODEL ZOOM & METRIC SLIDE UP)',
  'NEUMORPHIC BRIGHT MATTE CAROUSEL (ANIMATION: SOFT INSET PRESS & DEEP EMBOSSED CARD)',
  'BAUHAUS GEOMETRIC COLOR BLOCK CAROUSEL (ANIMATION: PRIMARY BLOCK SHIFT & ROTATE ICON SLIDE)',
  'CYBER ORGANIC BIOPUNK MARKETPLACE SLIDER (ANIMATION: BIO-CELL PULSE & TOXIC NEON HOVER TRACK)'
];

let newCaseBlock = `] : category === 'global-product-carousel' ? [\n`;
for (let i = 1; i <= 20; i++) {
  newCaseBlock += `      { id: 'global-product-carousel-${i}', title: 'Design ${i}: ${titles[i-1]}', description: 'Design: ${titles[i-1]}', previewComponent: <GlobalProductCarousel${i} /> },\n`;
}

// Replace existing global-product-carousel block
const regex = /\] : category === 'global-product-carousel' \? \[\s*([\s\S]*?)\s*\] : category === 'global-product-grid'/;
gridCode = gridCode.replace(regex, newCaseBlock + `] : category === 'global-product-grid'`);

fs.writeFileSync(gridFilePath, gridCode, 'utf8');
console.log('Successfully updated Global Product Carousel titles in SectionLibraryGrid.tsx');
